apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      restartPolicy: Always
      containers:
      - name: backend-feed-container
        imagePullPolicy: Always
        image: faithwenyi/udagram-api-feed #<ECR_REPOSITORY>
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: u-env-configmap
          - secretRef: 
              name: u-env-secret
          - secretRef:
              name: u-aws-secret